### ISSUE TITLE
Update merge options

### ISSUE THREAD

**Issue by MashiroK** [msanguineti/git-oneflow#796]
Hello Mirco. First, congratulations on making this tool, it really helps to comprehend and start with OneFlow. I just recently read the newer article Adam created on OneFlow, and I'd like to use your tool, except on the configs, I saw there's no option to merge using --squash, the method Adam recommend's the most. Would it be too much trouble to have this in your project?

I thank you kindly,
Jose Ferreira

**Comment by msanguineti** [comment]
Hello @MashiroK , sorry for the late reply.

Let me have a look at it. The thing is that I wanted to carry out some major reworks on this tool but never got round to do it.

Maybe the time has come :)
